### PR TITLE
Added a bunch of things from X11 headers needed for implementing clipboard interfacing

### PR DESCRIPTION
**Pull request by aweinstock314**

### CODE REVIEW

**Comment by aweinstock314** [comment]
This is failing to build on travis due to the dependency Xmu ("/usr/lib/x86_64-linux-gnu/libXmu.a" on the Debian system I'm using for development) not being found. Xmu contains the symbol _XA_CLIPBOARD (declared extern in "/usr/include/X11/Xmu/Atoms.h"), which is an X11 Atom (interned string) used as part of the protocol(s) involving the clipboard. How do I go about adding Xmu to the relevant dependencies list (assuming that's the correct way to go about resolving this)?

**Comment by Manishearth** [comment]
Add an `install` key:

```
install:
 - sudo apt-get install foobar
```

You will have to remove the `sudo: false` from the top, sadly

**Comment by metajack** [comment]
This will prevent it from using containerized builds, which means it will be slower to go through CI. If we can avoid an apt-get dep we should, but if we can't, we'll just have to live with the degraded performance.

**Comment by jdm** [comment]
I assume we want libxmu6-dev, not just libxmu6?

**Pull request merged**
